### ISSUE TITLE
TODO/FIXME Count 9

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-validation#22]
- [ ] FIXME: This is a stub
       Commit: (8ea35cf) Add basic credential schema and test stub.
       File:  [tests/001-schemas.js:323](https://github.com/digitalbazaar/bedrock-validation/blob/master/tests/001-schemas.js#L323)
       Matthew Collier commented 5 years ago

  - [ ] FIXME: add more tests, test for proper errors
       Commit: (f2e9cb1) Allow synchronous use of validation API and add schemas test.
       File:  [tests/001-schemas.js:10](https://github.com/digitalbazaar/bedrock-validation/blob/master/tests/001-schemas.js#L10)
       Dave Longley commented 5 years ago

  - [ ] FIXME: also support `frame` property later
       Commit: (578d042) Add json patch validators.
       File:  [schemas/sequencedPatch.js:15](https://github.com/digitalbazaar/bedrock-validation/blob/master/schemas/sequencedPatch.js#L15)
       Dave Longley commented 2 years ago

  - [ ] FIXME: improve context object validator
       Commit: (b5d36ee) Support validating JSON-LD context arrays.
       File:  [schemas/jsonldContext.js:45](https://github.com/digitalbazaar/bedrock-validation/blob/master/schemas/jsonldContext.js#L45)
       Dave Longley commented 5 years ago

  - [ ] FIXME: improve context object validator
       Commit: (134959c) Require context (url) parameter.
       File:  [schemas/jsonldContext.js:17](https://github.com/digitalbazaar/bedrock-validation/blob/master/schemas/jsonldContext.js#L17)
       Dave Longley commented 5 years ago

  - [ ] FIXME: more strictly validate properties based on value of `op`
       Commit: (578d042) Add json patch validators.
       File:  [schemas/jsonPatch.js:13](https://github.com/digitalbazaar/bedrock-validation/blob/master/schemas/jsonPatch.js#L13)
       Dave Longley commented 2 years ago

  - [ ] FIXME: improve credential context check
       Commit: (0e90609) Use jsonldContext to validate Credential @context.
       File:  [schemas/credential.js:18](https://github.com/digitalbazaar/bedrock-validation/blob/master/schemas/credential.js#L18)
       David I. Lehn commented 4 years ago

  - [ ] TODO: Improve this schema
       Commit: (8ea35cf) Add basic credential schema and test stub.
       File:  [schemas/credential.js:12](https://github.com/digitalbazaar/bedrock-validation/blob/master/schemas/credential.js#L12)
       Matthew Collier commented 5 years ago

  - [ ] FIXME: enable if ajv supports this parentSchema.errors property
       Commit: (e25d94d) Improve error reporting.
       File:  [lib/index.js:220](https://github.com/digitalbazaar/bedrock-validation/blob/master/lib/index.js#L220)
       Matthew Collier commented 2 years ago

       FIXME Count         8
       TODO Count          1
       Oldest Comment      5 years ago
       Oldest Commenter    Dave Longley
       Oldest Comment      FIXME: add more tests, test for proper errors

**Comment by JSAssassin** [comment]
Closing, opened individual issues for the FIXMEs on this list.
